# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assay_id', models.CharField(max_length=255, unique=True)),
                ('assay_name', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=255, unique=True)),
                ('sample_name', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='assay',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samples.Sample'),
        ),
    ]
